name: Android CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]  # Still trigger on tags
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Build Debug Binaries
      run: |
        ./gradlew assembleDebug  # Build debug APK
        ./gradlew bundleDebug    # Build debug AAB

    - name: Upload to GitHub Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/build/outputs/apk/debug/*.apk
          app/build/outputs/bundle/debug/*.aab
